// user registration/signup
export const USER_REGISTER_REQUEST = "USER/REGISTER_REQUEST"
export const USER_REGISTER_SUCCESS = "USER/REGISTER_SUCCESS"
export const USER_REGISTER_FAIL = "USER/REGISTER_FAIL"

// user registration/login
export const USER_LOGIN_REQUEST = "USER/LOGIN_REQUEST"
export const USER_LOGIN_SUCCESS = "USER/LOGIN_SUCCESS"
export const USER_LOGIN_FAIL = "USER/LOGIN_FAIL"

// user registration/session
export const USER_SESSION_REQUEST = "USER/SESSION_REQUEST"
export const USER_SESSION_SUCCESS = "USER/SESSION_SUCCESS"
export const USER_SESSION_FAIL = "USER/SESSION_FAIL"

// user registration/logout
export const USER_LOGOUT_REQUEST = "USER/LOGOUT_REQUEST"
export const USER_LOGOUT_SUCCESS = "USER/LOGOUT_SUCCESS"
export const USER_LOGOUT_FAIL = "USER/LOGOUT_FAIL"